name: build
on: push
jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - run: pip install github-action-utils
      - id: set-matrix
        run: python script.py

  build:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.prepare-matrix.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.matrix }}